import { MarkdownResponse } from '../generated_models';

const markdownResponseBody: MarkdownResponse = {
  output_type: 'markdown',
  value: `
### Overview
Below is a summary of results generated by our image classification pipeline.

1. **Image**: \`image1.jpg\`
   - **Top Prediction**: Cat (92%)
   - **Other Predictions**: Dog (5%), Rabbit (3%)

2. **Image**: \`image2.jpg\`
   - **Top Prediction**: Car (88%)
   - **Other Predictions**: Bicycle (7%), Train (5%)

3. **Image**: \`image3.jpg\`
    - **Top Prediction**: Apple (78%)
    - **Other Predictions**: Orange (15%), Banana (7%)
`,
  title: 'Image Classification Results',
} satisfies MarkdownResponse;

export default markdownResponseBody;
